// Golden tests for 200_window_height
//
// AUTO-GENERATED by `cargo xtask sync-golden`

use super::*;

// ============================================================================
// Test Operations (extracted from snapshot tests)
// ============================================================================

fn preset_window_heights_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetWindowHeight { id: Some(1) },
        Op::Communicate(1),
        Op::CompleteAnimations,
    ]
}

fn window_height_resize_ops() -> Vec<Op> {
    vec![
        Op::SetWindowHeight { id: Some(1), change: SizeChange::SetFixed(400) },
        Op::Communicate(1),
        Op::CompleteAnimations,
    ]
}

// ============================================================================
// LTR Tests
// ============================================================================

#[test]
fn preset_window_heights() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_window_heights_ops());
    assert_golden!(layout.snapshot(), "preset_window_heights");
}

#[test]
fn window_height_resize() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, window_height_resize_ops());
    assert_golden!(layout.snapshot(), "window_height_resize");
}

// ============================================================================
// RTL Tests
// ============================================================================

#[test]
fn preset_window_heights_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_window_heights_ops());
    assert_golden_rtl!(layout, "preset_window_heights");
}

#[test]
fn window_height_resize_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, window_height_resize_ops());
    assert_golden_rtl!(layout, "window_height_resize");
}

