//! Golden tests for 210_consume_expel
//!
//! AUTO-GENERATED by `cargo xtask sync-golden`
use super::*;
fn consume_into_column_with_tiles_ops() -> Vec<Op> {
    vec![
        Op::ConsumeWindowIntoColumn, Op::Communicate(2), Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}
fn expel_from_column_with_tiles_ops() -> Vec<Op> {
    vec![
        Op::ExpelWindowFromColumn, Op::Communicate(2), Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}
#[test]
fn consume_into_column_with_tiles() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, consume_into_column_with_tiles_ops());
    assert_golden!(layout.snapshot(), "consume_into_column_with_tiles");
}
#[test]
fn expel_from_column_with_tiles() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, expel_from_column_with_tiles_ops());
    assert_golden!(layout.snapshot(), "expel_from_column_with_tiles");
}
#[test]
fn consume_into_column_with_tiles_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, consume_into_column_with_tiles_ops());
    assert_golden_rtl!(layout, "consume_into_column_with_tiles");
}
#[test]
fn expel_from_column_with_tiles_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, expel_from_column_with_tiles_ops());
    assert_golden_rtl!(layout, "expel_from_column_with_tiles");
}
