// Golden tests for 090_focus_edge_cases
//
// AUTO-GENERATED by `cargo xtask sync-golden`

use super::*;

// ============================================================================
// Test Operations (extracted from snapshot tests)
// ============================================================================

fn focus_at_boundaries_1_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::FocusColumnLeft,
        Op::CompleteAnimations,
    ]
}

fn focus_at_boundaries_2_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::FocusColumnLeft,
        Op::CompleteAnimations,
    ]
}

// ============================================================================
// LTR Tests
// ============================================================================

#[test]
fn focus_at_boundaries_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, focus_at_boundaries_1_ops());
    assert_golden!(layout.snapshot(), "focus_at_boundaries_1");
}

#[test]
fn focus_at_boundaries_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, focus_at_boundaries_2_ops());
    assert_golden!(layout.snapshot(), "focus_at_boundaries_2");
}

// ============================================================================
// RTL Tests
// ============================================================================

#[test]
fn focus_at_boundaries_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, focus_at_boundaries_1_ops());
    assert_golden_rtl!(layout, "focus_at_boundaries_1");
}

#[test]
fn focus_at_boundaries_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, focus_at_boundaries_2_ops());
    assert_golden_rtl!(layout, "focus_at_boundaries_2");
}

