//! Golden tests for 230_column_display
//!
//! AUTO-GENERATED by `cargo xtask sync-golden`
use super::*;
fn set_column_display_tabbed_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft, Op::SetColumnDisplay(niri_ipc::ColumnDisplay::Tabbed),
        Op::CompleteAnimations,
    ]
}
fn toggle_column_tabbed_display_ops() -> Vec<Op> {
    vec![Op::FocusColumnLeft, Op::ToggleColumnTabbedDisplay, Op::CompleteAnimations,]
}
#[test]
fn set_column_display_tabbed() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, set_column_display_tabbed_ops());
    assert_golden!(layout.snapshot(), "set_column_display_tabbed");
}
#[test]
fn toggle_column_tabbed_display() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, toggle_column_tabbed_display_ops());
    assert_golden!(layout.snapshot(), "toggle_column_tabbed_display");
}
#[test]
fn set_column_display_tabbed_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, set_column_display_tabbed_ops());
    assert_golden_rtl!(layout, "set_column_display_tabbed");
}
#[test]
fn toggle_column_tabbed_display_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, toggle_column_tabbed_display_ops());
    assert_golden_rtl!(layout, "toggle_column_tabbed_display");
}
