//! Golden tests for 270_small_large_columns
//!
//! AUTO-GENERATED by `cargo xtask sync-golden`
use super::*;
fn single_very_wide_column_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetFixed(2000)), Op::Communicate(1),
        Op::CompleteAnimations,
    ]
}
fn very_small_column_with_proportion_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) }, Op::AddWindow { params :
        TestWindowParams::new(2) }, Op::AddWindow { params : TestWindowParams::new(3) },
        Op::Communicate(1), Op::Communicate(2), Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}
fn very_small_view_width_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetFixed(50)), Op::AddWindow { params :
        TestWindowParams::new(2) }, Op::SetColumnWidth(SizeChange::SetFixed(50)),
        Op::AddWindow { params : TestWindowParams::new(3) },
        Op::SetColumnWidth(SizeChange::SetFixed(50)), Op::Communicate(1),
        Op::Communicate(2), Op::Communicate(3), Op::CompleteAnimations,
    ]
}
#[test]
fn single_very_wide_column() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, single_very_wide_column_ops());
    assert_golden!(layout.snapshot(), "single_very_wide_column");
}
#[test]
fn very_small_column_with_proportion() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, very_small_column_with_proportion_ops());
    assert_golden!(layout.snapshot(), "very_small_column_with_proportion");
}
#[test]
fn very_small_view_width() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, very_small_view_width_ops());
    assert_golden!(layout.snapshot(), "very_small_view_width");
}
#[test]
fn single_very_wide_column_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, single_very_wide_column_ops());
    assert_golden_rtl!(layout, "single_very_wide_column");
}
#[test]
fn very_small_column_with_proportion_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, very_small_column_with_proportion_ops());
    assert_golden_rtl!(layout, "very_small_column_with_proportion");
}
#[test]
fn very_small_view_width_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, very_small_view_width_ops());
    assert_golden_rtl!(layout, "very_small_view_width");
}
