// Golden tests for 140_column_move_first_last
//
// AUTO-GENERATED by `cargo xtask sync-golden`

use super::*;

// ============================================================================
// Test Operations (extracted from snapshot tests)
// ============================================================================

fn move_column_to_first_ops() -> Vec<Op> {
    vec![
        Op::MoveColumnToFirst,
        Op::Communicate(1),
        Op::Communicate(2),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn move_column_to_last_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::FocusColumnLeft,
        Op::MoveColumnToLast,
        Op::Communicate(1),
        Op::Communicate(2),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

// ============================================================================
// LTR Tests
// ============================================================================

#[test]
fn move_column_to_first() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, move_column_to_first_ops());
    assert_golden!(layout.snapshot(), "move_column_to_first");
}

#[test]
fn move_column_to_last() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, move_column_to_last_ops());
    assert_golden!(layout.snapshot(), "move_column_to_last");
}

// ============================================================================
// RTL Tests
// ============================================================================

#[test]
fn move_column_to_first_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, move_column_to_first_ops());
    assert_golden_rtl!(layout, "move_column_to_first");
}

#[test]
fn move_column_to_last_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, move_column_to_last_ops());
    assert_golden_rtl!(layout, "move_column_to_last");
}

