//! Golden tests for 170_tiles_multiple
//!
//! AUTO-GENERATED by `cargo xtask sync-golden`
use super::*;
fn four_tiles_in_column_equal_height_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(50.0)), Op::AddWindow { params :
        TestWindowParams::new(2) }, Op::AddWindow { params : TestWindowParams::new(3) },
        Op::AddWindow { params : TestWindowParams::new(4) }, Op::Communicate(1),
        Op::Communicate(2), Op::Communicate(3), Op::Communicate(4),
        Op::CompleteAnimations,
    ]
}
fn three_tiles_in_column_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(50.0)), Op::AddWindow { params :
        TestWindowParams::new(2) }, Op::AddWindow { params : TestWindowParams::new(3) },
        Op::Communicate(1), Op::Communicate(2), Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}
fn tiles_with_mixed_heights_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(50.0)), Op::AddWindow { params :
        TestWindowParams::new(2) }, Op::SetWindowHeight { id : Some(2), change :
        SizeChange::SetFixed(200) }, Op::AddWindow { params : TestWindowParams::new(3) },
        Op::SetWindowHeight { id : Some(3), change : SizeChange::SetFixed(300) },
        Op::Communicate(1), Op::Communicate(2), Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}
fn tiles_with_preset_heights_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(50.0)), Op::AddWindow { params :
        TestWindowParams::new(2) }, Op::SwitchPresetWindowHeight { id : Some(2) },
        Op::AddWindow { params : TestWindowParams::new(3) }, Op::SwitchPresetWindowHeight
        { id : Some(3) }, Op::SwitchPresetWindowHeight { id : Some(3) },
        Op::Communicate(1), Op::Communicate(2), Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}
#[test]
fn four_tiles_in_column_equal_height() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, four_tiles_in_column_equal_height_ops());
    assert_golden!(layout.snapshot(), "four_tiles_in_column_equal_height");
}
#[test]
fn three_tiles_in_column() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, three_tiles_in_column_ops());
    assert_golden!(layout.snapshot(), "three_tiles_in_column");
}
#[test]
fn tiles_with_mixed_heights() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, tiles_with_mixed_heights_ops());
    assert_golden!(layout.snapshot(), "tiles_with_mixed_heights");
}
#[test]
fn tiles_with_preset_heights() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, tiles_with_preset_heights_ops());
    assert_golden!(layout.snapshot(), "tiles_with_preset_heights");
}
#[test]
fn four_tiles_in_column_equal_height_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, four_tiles_in_column_equal_height_ops());
    assert_golden_rtl!(layout, "four_tiles_in_column_equal_height");
}
#[test]
fn three_tiles_in_column_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, three_tiles_in_column_ops());
    assert_golden_rtl!(layout, "three_tiles_in_column");
}
#[test]
fn tiles_with_mixed_heights_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, tiles_with_mixed_heights_ops());
    assert_golden_rtl!(layout, "tiles_with_mixed_heights");
}
#[test]
fn tiles_with_preset_heights_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, tiles_with_preset_heights_ops());
    assert_golden_rtl!(layout, "tiles_with_preset_heights");
}
