//! Golden tests for 160_alternative_presets
//!
//! AUTO-GENERATED by `cargo xtask sync-golden`
use super::*;
fn preset_two_fifths_gaps_struts_combined_1_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft, Op::SwitchPresetColumnWidth, Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}
fn preset_two_fifths_gaps_struts_combined_2_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft, Op::SwitchPresetColumnWidth, Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}
fn preset_two_fifths_tiles_1_ops() -> Vec<Op> {
    vec![Op::FocusColumnLeft, Op::CompleteAnimations,]
}
fn preset_two_fifths_tiles_2_ops() -> Vec<Op> {
    vec![Op::FocusColumnLeft, Op::CompleteAnimations,]
}
fn preset_two_fifths_tiles_3_ops() -> Vec<Op> {
    vec![Op::FocusColumnLeft, Op::CompleteAnimations,]
}
fn preset_two_fifths_tiles_4_ops() -> Vec<Op> {
    vec![Op::FocusColumnLeft, Op::CompleteAnimations,]
}
fn preset_two_fifths_tiles_5_ops() -> Vec<Op> {
    vec![Op::FocusColumnLeft, Op::CompleteAnimations,]
}
fn preset_two_fifths_with_gaps_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) }, Op::AddWindow { params :
        TestWindowParams::new(2) }, Op::AddWindow { params : TestWindowParams::new(3) },
        Op::Communicate(1), Op::Communicate(2), Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}
fn preset_two_fifths_with_struts_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) }, Op::AddWindow { params :
        TestWindowParams::new(2) }, Op::AddWindow { params : TestWindowParams::new(3) },
        Op::Communicate(1), Op::Communicate(2), Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}
#[test]
fn preset_two_fifths_gaps_struts_combined_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_two_fifths_gaps_struts_combined_1_ops());
    assert_golden!(layout.snapshot(), "preset_two_fifths_gaps_struts_combined_1");
}
#[test]
fn preset_two_fifths_gaps_struts_combined_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_two_fifths_gaps_struts_combined_2_ops());
    assert_golden!(layout.snapshot(), "preset_two_fifths_gaps_struts_combined_2");
}
#[test]
fn preset_two_fifths_tiles_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_two_fifths_tiles_1_ops());
    assert_golden!(layout.snapshot(), "preset_two_fifths_tiles_1");
}
#[test]
fn preset_two_fifths_tiles_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_two_fifths_tiles_2_ops());
    assert_golden!(layout.snapshot(), "preset_two_fifths_tiles_2");
}
#[test]
fn preset_two_fifths_tiles_3() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_two_fifths_tiles_3_ops());
    assert_golden!(layout.snapshot(), "preset_two_fifths_tiles_3");
}
#[test]
fn preset_two_fifths_tiles_4() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_two_fifths_tiles_4_ops());
    assert_golden!(layout.snapshot(), "preset_two_fifths_tiles_4");
}
#[test]
fn preset_two_fifths_tiles_5() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_two_fifths_tiles_5_ops());
    assert_golden!(layout.snapshot(), "preset_two_fifths_tiles_5");
}
#[test]
fn preset_two_fifths_with_gaps() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_two_fifths_with_gaps_ops());
    assert_golden!(layout.snapshot(), "preset_two_fifths_with_gaps");
}
#[test]
fn preset_two_fifths_with_struts() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_two_fifths_with_struts_ops());
    assert_golden!(layout.snapshot(), "preset_two_fifths_with_struts");
}
#[test]
fn preset_two_fifths_gaps_struts_combined_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_two_fifths_gaps_struts_combined_1_ops());
    assert_golden_rtl!(layout, "preset_two_fifths_gaps_struts_combined_1");
}
#[test]
fn preset_two_fifths_gaps_struts_combined_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_two_fifths_gaps_struts_combined_2_ops());
    assert_golden_rtl!(layout, "preset_two_fifths_gaps_struts_combined_2");
}
#[test]
fn preset_two_fifths_tiles_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_two_fifths_tiles_1_ops());
    assert_golden_rtl!(layout, "preset_two_fifths_tiles_1");
}
#[test]
fn preset_two_fifths_tiles_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_two_fifths_tiles_2_ops());
    assert_golden_rtl!(layout, "preset_two_fifths_tiles_2");
}
#[test]
fn preset_two_fifths_tiles_3_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_two_fifths_tiles_3_ops());
    assert_golden_rtl!(layout, "preset_two_fifths_tiles_3");
}
#[test]
fn preset_two_fifths_tiles_4_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_two_fifths_tiles_4_ops());
    assert_golden_rtl!(layout, "preset_two_fifths_tiles_4");
}
#[test]
fn preset_two_fifths_tiles_5_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_two_fifths_tiles_5_ops());
    assert_golden_rtl!(layout, "preset_two_fifths_tiles_5");
}
#[test]
fn preset_two_fifths_with_gaps_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_two_fifths_with_gaps_ops());
    assert_golden_rtl!(layout, "preset_two_fifths_with_gaps");
}
#[test]
fn preset_two_fifths_with_struts_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_two_fifths_with_struts_ops());
    assert_golden_rtl!(layout, "preset_two_fifths_with_struts");
}
