#!/bin/sh

if [ -n "$SHELL" ] &&
   grep -q "$SHELL" /etc/shells &&
   ! (echo "$SHELL" | grep -q "false") &&
   ! (echo "$SHELL" | grep -q "nologin"); then
  if [ "$1" != '-l' ]; then
    exec bash -c "exec -l '$SHELL' -c '$0 -l $*'"
  else
    shift
  fi
fi

# Make sure there's no already running session.
if systemctl --user -q is-active niri.service; then
  echo 'A niri session is already running.'
  exit 1
fi

# Reset failed state of all user units.
systemctl --user reset-failed

# Start niri and wait for it to terminate.
systemctl --user --wait start niri.service

# Force stop of grahical-session.target.
systemctl --user start --job-mode=replace-irreversibly niri-shutdown.target

# Unset environment that we've set.
systemctl --user unset-environment WAYLAND_DISPLAY XDG_SESSION_TYPE XDG_CURRENT_DESKTOP NIRI_SOCKET
