// Golden tests for 150_preset_width
//
// AUTO-GENERATED by `cargo xtask sync-golden`

use super::*;

// ============================================================================
// Test Operations (extracted from snapshot tests)
// ============================================================================

fn preset_cycling_middle_column_with_overflow_1_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidth,
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn preset_cycling_middle_column_with_overflow_2_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidth,
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn preset_cycling_middle_column_with_overflow_3_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidth,
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn preset_cycling_middle_column_with_overflow_4_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidth,
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn preset_cycling_rightmost_column_with_overflow_1_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidth,
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn preset_cycling_rightmost_column_with_overflow_2_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidth,
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn preset_cycling_rightmost_column_with_overflow_3_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidth,
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn preset_cycling_rightmost_column_with_overflow_4_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidth,
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn preset_cycling_two_fifths_to_four_fifths_1_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidth,
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn preset_cycling_two_fifths_to_four_fifths_2_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidth,
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn preset_cycling_two_fifths_to_four_fifths_3_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidth,
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn preset_cycling_two_fifths_to_four_fifths_4_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidth,
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn preset_two_fifths_gaps_struts_combined_1_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::SwitchPresetColumnWidth,
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn preset_two_fifths_gaps_struts_combined_2_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::SwitchPresetColumnWidth,
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn preset_width_index_cycles_backward_1_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidthBack,
        Op::Communicate(1),
        Op::CompleteAnimations,
    ]
}

fn preset_width_index_cycles_backward_2_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidthBack,
        Op::Communicate(1),
        Op::CompleteAnimations,
    ]
}

fn preset_width_index_cycles_correctly_1_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidth,
        Op::Communicate(1),
        Op::CompleteAnimations,
    ]
}

fn preset_width_index_cycles_correctly_2_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidth,
        Op::Communicate(1),
        Op::CompleteAnimations,
    ]
}

fn preset_width_index_cycles_correctly_3_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidth,
        Op::Communicate(1),
        Op::CompleteAnimations,
    ]
}

fn preset_width_index_cycles_correctly_4_ops() -> Vec<Op> {
    vec![
        Op::SwitchPresetColumnWidth,
        Op::Communicate(1),
        Op::CompleteAnimations,
    ]
}

// ============================================================================
// LTR Tests
// ============================================================================

#[test]
fn preset_cycling_middle_column_with_overflow_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_cycling_middle_column_with_overflow_1_ops());
    assert_golden!(layout.snapshot(), "preset_cycling_middle_column_with_overflow_1");
}

#[test]
fn preset_cycling_middle_column_with_overflow_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_cycling_middle_column_with_overflow_2_ops());
    assert_golden!(layout.snapshot(), "preset_cycling_middle_column_with_overflow_2");
}

#[test]
fn preset_cycling_middle_column_with_overflow_3() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_cycling_middle_column_with_overflow_3_ops());
    assert_golden!(layout.snapshot(), "preset_cycling_middle_column_with_overflow_3");
}

#[test]
fn preset_cycling_middle_column_with_overflow_4() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_cycling_middle_column_with_overflow_4_ops());
    assert_golden!(layout.snapshot(), "preset_cycling_middle_column_with_overflow_4");
}

#[test]
fn preset_cycling_rightmost_column_with_overflow_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_cycling_rightmost_column_with_overflow_1_ops());
    assert_golden!(layout.snapshot(), "preset_cycling_rightmost_column_with_overflow_1");
}

#[test]
fn preset_cycling_rightmost_column_with_overflow_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_cycling_rightmost_column_with_overflow_2_ops());
    assert_golden!(layout.snapshot(), "preset_cycling_rightmost_column_with_overflow_2");
}

#[test]
fn preset_cycling_rightmost_column_with_overflow_3() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_cycling_rightmost_column_with_overflow_3_ops());
    assert_golden!(layout.snapshot(), "preset_cycling_rightmost_column_with_overflow_3");
}

#[test]
fn preset_cycling_rightmost_column_with_overflow_4() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_cycling_rightmost_column_with_overflow_4_ops());
    assert_golden!(layout.snapshot(), "preset_cycling_rightmost_column_with_overflow_4");
}

#[test]
fn preset_cycling_two_fifths_to_four_fifths_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_cycling_two_fifths_to_four_fifths_1_ops());
    assert_golden!(layout.snapshot(), "preset_cycling_two_fifths_to_four_fifths_1");
}

#[test]
fn preset_cycling_two_fifths_to_four_fifths_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_cycling_two_fifths_to_four_fifths_2_ops());
    assert_golden!(layout.snapshot(), "preset_cycling_two_fifths_to_four_fifths_2");
}

#[test]
fn preset_cycling_two_fifths_to_four_fifths_3() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_cycling_two_fifths_to_four_fifths_3_ops());
    assert_golden!(layout.snapshot(), "preset_cycling_two_fifths_to_four_fifths_3");
}

#[test]
fn preset_cycling_two_fifths_to_four_fifths_4() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_cycling_two_fifths_to_four_fifths_4_ops());
    assert_golden!(layout.snapshot(), "preset_cycling_two_fifths_to_four_fifths_4");
}

#[test]
fn preset_two_fifths_gaps_struts_combined_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_two_fifths_gaps_struts_combined_1_ops());
    assert_golden!(layout.snapshot(), "preset_two_fifths_gaps_struts_combined_1");
}

#[test]
fn preset_two_fifths_gaps_struts_combined_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_two_fifths_gaps_struts_combined_2_ops());
    assert_golden!(layout.snapshot(), "preset_two_fifths_gaps_struts_combined_2");
}

#[test]
fn preset_width_index_cycles_backward_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_width_index_cycles_backward_1_ops());
    assert_golden!(layout.snapshot(), "preset_width_index_cycles_backward_1");
}

#[test]
fn preset_width_index_cycles_backward_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_width_index_cycles_backward_2_ops());
    assert_golden!(layout.snapshot(), "preset_width_index_cycles_backward_2");
}

#[test]
fn preset_width_index_cycles_correctly_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_width_index_cycles_correctly_1_ops());
    assert_golden!(layout.snapshot(), "preset_width_index_cycles_correctly_1");
}

#[test]
fn preset_width_index_cycles_correctly_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_width_index_cycles_correctly_2_ops());
    assert_golden!(layout.snapshot(), "preset_width_index_cycles_correctly_2");
}

#[test]
fn preset_width_index_cycles_correctly_3() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_width_index_cycles_correctly_3_ops());
    assert_golden!(layout.snapshot(), "preset_width_index_cycles_correctly_3");
}

#[test]
fn preset_width_index_cycles_correctly_4() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_width_index_cycles_correctly_4_ops());
    assert_golden!(layout.snapshot(), "preset_width_index_cycles_correctly_4");
}

// ============================================================================
// RTL Tests
// ============================================================================

#[test]
fn preset_cycling_middle_column_with_overflow_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_cycling_middle_column_with_overflow_1_ops());
    assert_golden_rtl!(layout, "preset_cycling_middle_column_with_overflow_1");
}

#[test]
fn preset_cycling_middle_column_with_overflow_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_cycling_middle_column_with_overflow_2_ops());
    assert_golden_rtl!(layout, "preset_cycling_middle_column_with_overflow_2");
}

#[test]
fn preset_cycling_middle_column_with_overflow_3_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_cycling_middle_column_with_overflow_3_ops());
    assert_golden_rtl!(layout, "preset_cycling_middle_column_with_overflow_3");
}

#[test]
fn preset_cycling_middle_column_with_overflow_4_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_cycling_middle_column_with_overflow_4_ops());
    assert_golden_rtl!(layout, "preset_cycling_middle_column_with_overflow_4");
}

#[test]
fn preset_cycling_rightmost_column_with_overflow_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_cycling_rightmost_column_with_overflow_1_ops());
    assert_golden_rtl!(layout, "preset_cycling_rightmost_column_with_overflow_1");
}

#[test]
fn preset_cycling_rightmost_column_with_overflow_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_cycling_rightmost_column_with_overflow_2_ops());
    assert_golden_rtl!(layout, "preset_cycling_rightmost_column_with_overflow_2");
}

#[test]
fn preset_cycling_rightmost_column_with_overflow_3_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_cycling_rightmost_column_with_overflow_3_ops());
    assert_golden_rtl!(layout, "preset_cycling_rightmost_column_with_overflow_3");
}

#[test]
fn preset_cycling_rightmost_column_with_overflow_4_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_cycling_rightmost_column_with_overflow_4_ops());
    assert_golden_rtl!(layout, "preset_cycling_rightmost_column_with_overflow_4");
}

#[test]
fn preset_cycling_two_fifths_to_four_fifths_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_cycling_two_fifths_to_four_fifths_1_ops());
    assert_golden_rtl!(layout, "preset_cycling_two_fifths_to_four_fifths_1");
}

#[test]
fn preset_cycling_two_fifths_to_four_fifths_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_cycling_two_fifths_to_four_fifths_2_ops());
    assert_golden_rtl!(layout, "preset_cycling_two_fifths_to_four_fifths_2");
}

#[test]
fn preset_cycling_two_fifths_to_four_fifths_3_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_cycling_two_fifths_to_four_fifths_3_ops());
    assert_golden_rtl!(layout, "preset_cycling_two_fifths_to_four_fifths_3");
}

#[test]
fn preset_cycling_two_fifths_to_four_fifths_4_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_cycling_two_fifths_to_four_fifths_4_ops());
    assert_golden_rtl!(layout, "preset_cycling_two_fifths_to_four_fifths_4");
}

#[test]
fn preset_two_fifths_gaps_struts_combined_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_two_fifths_gaps_struts_combined_1_ops());
    assert_golden_rtl!(layout, "preset_two_fifths_gaps_struts_combined_1");
}

#[test]
fn preset_two_fifths_gaps_struts_combined_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_two_fifths_gaps_struts_combined_2_ops());
    assert_golden_rtl!(layout, "preset_two_fifths_gaps_struts_combined_2");
}

#[test]
fn preset_width_index_cycles_backward_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_width_index_cycles_backward_1_ops());
    assert_golden_rtl!(layout, "preset_width_index_cycles_backward_1");
}

#[test]
fn preset_width_index_cycles_backward_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_width_index_cycles_backward_2_ops());
    assert_golden_rtl!(layout, "preset_width_index_cycles_backward_2");
}

#[test]
fn preset_width_index_cycles_correctly_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_width_index_cycles_correctly_1_ops());
    assert_golden_rtl!(layout, "preset_width_index_cycles_correctly_1");
}

#[test]
fn preset_width_index_cycles_correctly_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_width_index_cycles_correctly_2_ops());
    assert_golden_rtl!(layout, "preset_width_index_cycles_correctly_2");
}

#[test]
fn preset_width_index_cycles_correctly_3_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_width_index_cycles_correctly_3_ops());
    assert_golden_rtl!(layout, "preset_width_index_cycles_correctly_3");
}

#[test]
fn preset_width_index_cycles_correctly_4_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_width_index_cycles_correctly_4_ops());
    assert_golden_rtl!(layout, "preset_width_index_cycles_correctly_4");
}

