// Golden tests for 350_anim_resize
//
// AUTO-GENERATED by `cargo xtask sync-golden`

use super::*;

// ============================================================================
// Test Operations (extracted from snapshot tests)
// ============================================================================

fn anim_resize_adjust_proportion_1_ops() -> Vec<Op> {
    vec![
        Op::SetColumnWidth(SizeChange::AdjustProportion(10.0)),
        Op::Communicate(1),
    ]
}

fn anim_resize_adjust_proportion_2_ops() -> Vec<Op> {
    // No ops extracted - define manually
    vec![]
}

fn anim_resize_non_preset_fixed_1_ops() -> Vec<Op> {
    vec![
        Op::SetColumnWidth(SizeChange::SetFixed(800)),
        Op::Communicate(1),
    ]
}

fn anim_resize_non_preset_fixed_2_ops() -> Vec<Op> {
    // No ops extracted - define manually
    vec![]
}

// ============================================================================
// LTR Tests
// ============================================================================

#[test]
fn anim_resize_adjust_proportion_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, anim_resize_adjust_proportion_1_ops());
    assert_golden!(layout.snapshot(), "anim_resize_adjust_proportion_1");
}

#[test]
fn anim_resize_adjust_proportion_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, anim_resize_adjust_proportion_2_ops());
    assert_golden!(layout.snapshot(), "anim_resize_adjust_proportion_2");
}

#[test]
fn anim_resize_non_preset_fixed_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, anim_resize_non_preset_fixed_1_ops());
    assert_golden!(layout.snapshot(), "anim_resize_non_preset_fixed_1");
}

#[test]
fn anim_resize_non_preset_fixed_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, anim_resize_non_preset_fixed_2_ops());
    assert_golden!(layout.snapshot(), "anim_resize_non_preset_fixed_2");
}

// ============================================================================
// RTL Tests
// ============================================================================

#[test]
fn anim_resize_adjust_proportion_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, anim_resize_adjust_proportion_1_ops());
    assert_golden_rtl!(layout, "anim_resize_adjust_proportion_1");
}

#[test]
fn anim_resize_adjust_proportion_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, anim_resize_adjust_proportion_2_ops());
    assert_golden_rtl!(layout, "anim_resize_adjust_proportion_2");
}

#[test]
fn anim_resize_non_preset_fixed_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, anim_resize_non_preset_fixed_1_ops());
    assert_golden_rtl!(layout, "anim_resize_non_preset_fixed_1");
}

#[test]
fn anim_resize_non_preset_fixed_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, anim_resize_non_preset_fixed_2_ops());
    assert_golden_rtl!(layout, "anim_resize_non_preset_fixed_2");
}

