//! Golden tests for 180_tiles_focus
//!
//! AUTO-GENERATED by `cargo xtask sync-golden`
use super::*;
fn focus_window_down_in_column_1_ops() -> Vec<Op> {
    vec![Op::FocusWindowDown, Op::CompleteAnimations,]
}
fn focus_window_down_in_column_2_ops() -> Vec<Op> {
    vec![Op::FocusWindowDown, Op::CompleteAnimations,]
}
fn focus_window_up_in_column_ops() -> Vec<Op> {
    vec![Op::FocusColumnLeft, Op::FocusWindowUp, Op::CompleteAnimations,]
}
#[test]
fn focus_window_down_in_column_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, focus_window_down_in_column_1_ops());
    assert_golden!(layout.snapshot(), "focus_window_down_in_column_1");
}
#[test]
fn focus_window_down_in_column_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, focus_window_down_in_column_2_ops());
    assert_golden!(layout.snapshot(), "focus_window_down_in_column_2");
}
#[test]
fn focus_window_up_in_column() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, focus_window_up_in_column_ops());
    assert_golden!(layout.snapshot(), "focus_window_up_in_column");
}
#[test]
fn focus_window_down_in_column_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, focus_window_down_in_column_1_ops());
    assert_golden_rtl!(layout, "focus_window_down_in_column_1");
}
#[test]
fn focus_window_down_in_column_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, focus_window_down_in_column_2_ops());
    assert_golden_rtl!(layout, "focus_window_down_in_column_2");
}
#[test]
fn focus_window_up_in_column_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, focus_window_up_in_column_ops());
    assert_golden_rtl!(layout, "focus_window_up_in_column");
}
