// Golden tests for 100_window_lifecycle
//
// AUTO-GENERATED by `cargo xtask sync-golden`

use super::*;

// ============================================================================
// Test Operations (extracted from snapshot tests)
// ============================================================================

fn window_opening_closing_sequences_1_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params: TestWindowParams::new(4) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::Communicate(1),
        Op::Communicate(3),
        Op::Communicate(4),
        Op::CompleteAnimations,
    ]
}

fn window_opening_closing_sequences_2_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params: TestWindowParams::new(4) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::Communicate(1),
        Op::Communicate(3),
        Op::Communicate(4),
        Op::CompleteAnimations,
    ]
}

// ============================================================================
// LTR Tests
// ============================================================================

#[test]
fn window_opening_closing_sequences_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, window_opening_closing_sequences_1_ops());
    assert_golden!(layout.snapshot(), "window_opening_closing_sequences_1");
}

#[test]
fn window_opening_closing_sequences_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, window_opening_closing_sequences_2_ops());
    assert_golden!(layout.snapshot(), "window_opening_closing_sequences_2");
}

// ============================================================================
// RTL Tests
// ============================================================================

#[test]
fn window_opening_closing_sequences_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, window_opening_closing_sequences_1_ops());
    assert_golden_rtl!(layout, "window_opening_closing_sequences_1");
}

#[test]
fn window_opening_closing_sequences_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, window_opening_closing_sequences_2_ops());
    assert_golden_rtl!(layout, "window_opening_closing_sequences_2");
}

