// Golden tests for 260_center_focused
//
// AUTO-GENERATED by `cargo xtask sync-golden`

use super::*;

// ============================================================================
// Test Operations (extracted from snapshot tests)
// ============================================================================

fn always_center_single_column_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params: TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::Communicate(1),
        Op::CompleteAnimations,
    ]
}

fn center_focused_column_always_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params: TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::AddWindow { params: TestWindowParams::new(2) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::Communicate(1),
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn center_focused_column_on_overflow_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params: TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::AddWindow { params: TestWindowParams::new(2) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::AddWindow { params: TestWindowParams::new(3) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::AddWindow { params: TestWindowParams::new(4) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::Communicate(1),
        Op::Communicate(2),
        Op::Communicate(3),
        Op::Communicate(4),
        Op::CompleteAnimations,
    ]
}

// ============================================================================
// LTR Tests
// ============================================================================

#[test]
fn always_center_single_column() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, always_center_single_column_ops());
    assert_golden!(layout.snapshot(), "always_center_single_column");
}

#[test]
fn center_focused_column_always() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, center_focused_column_always_ops());
    assert_golden!(layout.snapshot(), "center_focused_column_always");
}

#[test]
fn center_focused_column_on_overflow() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, center_focused_column_on_overflow_ops());
    assert_golden!(layout.snapshot(), "center_focused_column_on_overflow");
}

// ============================================================================
// RTL Tests
// ============================================================================

#[test]
fn always_center_single_column_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, always_center_single_column_ops());
    assert_golden_rtl!(layout, "always_center_single_column");
}

#[test]
fn center_focused_column_always_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, center_focused_column_always_ops());
    assert_golden_rtl!(layout, "center_focused_column_always");
}

#[test]
fn center_focused_column_on_overflow_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, center_focused_column_on_overflow_ops());
    assert_golden_rtl!(layout, "center_focused_column_on_overflow");
}

