// Golden tests for 060_focus_movement
//
// AUTO-GENERATED by `cargo xtask sync-golden`

use super::*;

// ============================================================================
// Test Operations (extracted from snapshot tests)
// ============================================================================

fn focus_movement_1_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnRight,
        Op::FocusColumnRight,
        Op::FocusColumnRight,
        Op::CompleteAnimations,
    ]
}

fn focus_movement_2_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnRight,
        Op::FocusColumnRight,
        Op::FocusColumnRight,
        Op::CompleteAnimations,
    ]
}

fn focus_movement_3_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnRight,
        Op::FocusColumnRight,
        Op::FocusColumnRight,
        Op::CompleteAnimations,
    ]
}

fn focus_movement_4_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnRight,
        Op::FocusColumnRight,
        Op::FocusColumnRight,
        Op::CompleteAnimations,
    ]
}

fn focus_with_mixed_widths_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::CompleteAnimations,
    ]
}

// ============================================================================
// LTR Tests
// ============================================================================

#[test]
fn focus_movement_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, focus_movement_1_ops());
    assert_golden!(layout.snapshot(), "focus_movement_1");
}

#[test]
fn focus_movement_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, focus_movement_2_ops());
    assert_golden!(layout.snapshot(), "focus_movement_2");
}

#[test]
fn focus_movement_3() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, focus_movement_3_ops());
    assert_golden!(layout.snapshot(), "focus_movement_3");
}

#[test]
fn focus_movement_4() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, focus_movement_4_ops());
    assert_golden!(layout.snapshot(), "focus_movement_4");
}

#[test]
fn focus_with_mixed_widths() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, focus_with_mixed_widths_ops());
    assert_golden!(layout.snapshot(), "focus_with_mixed_widths");
}

// ============================================================================
// RTL Tests
// ============================================================================

#[test]
fn focus_movement_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, focus_movement_1_ops());
    assert_golden_rtl!(layout, "focus_movement_1");
}

#[test]
fn focus_movement_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, focus_movement_2_ops());
    assert_golden_rtl!(layout, "focus_movement_2");
}

#[test]
fn focus_movement_3_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, focus_movement_3_ops());
    assert_golden_rtl!(layout, "focus_movement_3");
}

#[test]
fn focus_movement_4_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, focus_movement_4_ops());
    assert_golden_rtl!(layout, "focus_movement_4");
}

#[test]
fn focus_with_mixed_widths_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, focus_with_mixed_widths_ops());
    assert_golden_rtl!(layout, "focus_with_mixed_widths");
}

