//! Golden tests for 280_overflow_scenarios
//!
//! AUTO-GENERATED by `cargo xtask sync-golden`
use super::*;
fn many_columns_overflow_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) }, Op::AddWindow { params :
        TestWindowParams::new(2) }, Op::AddWindow { params : TestWindowParams::new(3) },
        Op::AddWindow { params : TestWindowParams::new(4) }, Op::AddWindow { params :
        TestWindowParams::new(5) }, Op::AddWindow { params : TestWindowParams::new(6) },
        Op::AddWindow { params : TestWindowParams::new(7) }, Op::AddWindow { params :
        TestWindowParams::new(8) }, Op::AddWindow { params : TestWindowParams::new(9) },
        Op::AddWindow { params : TestWindowParams::new(10) }, Op::Communicate(1),
        Op::Communicate(2), Op::Communicate(3), Op::Communicate(4), Op::Communicate(5),
        Op::Communicate(6), Op::Communicate(7), Op::Communicate(8), Op::Communicate(9),
        Op::Communicate(10), Op::CompleteAnimations,
    ]
}
#[test]
fn many_columns_overflow() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, many_columns_overflow_ops());
    assert_golden!(layout.snapshot(), "many_columns_overflow");
}
#[test]
fn many_columns_overflow_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, many_columns_overflow_ops());
    assert_golden_rtl!(layout, "many_columns_overflow");
}
