//! Golden tests for 300_extreme_config
//!
//! AUTO-GENERATED by `cargo xtask sync-golden`
use super::*;
fn very_large_gaps_extreme_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)), Op::Communicate(1),
        Op::CompleteAnimations,
    ]
}
fn very_large_struts_extreme_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) }, Op::Communicate(1),
        Op::CompleteAnimations,
    ]
}
#[test]
fn very_large_gaps_extreme() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, very_large_gaps_extreme_ops());
    assert_golden!(layout.snapshot(), "very_large_gaps_extreme");
}
#[test]
fn very_large_struts_extreme() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, very_large_struts_extreme_ops());
    assert_golden!(layout.snapshot(), "very_large_struts_extreme");
}
#[test]
fn very_large_gaps_extreme_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, very_large_gaps_extreme_ops());
    assert_golden_rtl!(layout, "very_large_gaps_extreme");
}
#[test]
fn very_large_struts_extreme_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, very_large_struts_extreme_ops());
    assert_golden_rtl!(layout, "very_large_struts_extreme");
}
