// Golden tests for 040_view_offset
//
// AUTO-GENERATED by `cargo xtask sync-golden`

use super::*;

// ============================================================================
// Test Operations (extracted from snapshot tests)
// ============================================================================

fn view_offset_clamped_at_zero_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params: TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::Communicate(1),
        Op::CompleteAnimations,
    ]
}

fn view_offset_clamped_with_small_columns_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params: TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetFixed(200)),
        Op::AddWindow { params: TestWindowParams::new(2) },
        Op::SetColumnWidth(SizeChange::SetFixed(200)),
        Op::Communicate(1),
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn view_offset_with_overflow_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params: TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::AddWindow { params: TestWindowParams::new(2) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::AddWindow { params: TestWindowParams::new(3) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::AddWindow { params: TestWindowParams::new(4) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::Communicate(1),
        Op::Communicate(2),
        Op::Communicate(3),
        Op::Communicate(4),
        Op::CompleteAnimations,
    ]
}

// ============================================================================
// LTR Tests
// ============================================================================

#[test]
fn view_offset_clamped_at_zero() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, view_offset_clamped_at_zero_ops());
    assert_golden!(layout.snapshot(), "view_offset_clamped_at_zero");
}

#[test]
fn view_offset_clamped_with_small_columns() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, view_offset_clamped_with_small_columns_ops());
    assert_golden!(layout.snapshot(), "view_offset_clamped_with_small_columns");
}

#[test]
fn view_offset_with_overflow() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, view_offset_with_overflow_ops());
    assert_golden!(layout.snapshot(), "view_offset_with_overflow");
}

// ============================================================================
// RTL Tests
// ============================================================================

#[test]
fn view_offset_clamped_at_zero_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, view_offset_clamped_at_zero_ops());
    assert_golden_rtl!(layout, "view_offset_clamped_at_zero");
}

#[test]
fn view_offset_clamped_with_small_columns_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, view_offset_clamped_with_small_columns_ops());
    assert_golden_rtl!(layout, "view_offset_clamped_with_small_columns");
}

#[test]
fn view_offset_with_overflow_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, view_offset_with_overflow_ops());
    assert_golden_rtl!(layout, "view_offset_with_overflow");
}

