//! Golden tests for 310_default_widths
//!
//! AUTO-GENERATED by `cargo xtask sync-golden`
use super::*;
fn default_column_width_fixed_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) }, Op::Communicate(1),
        Op::CompleteAnimations,
    ]
}
fn different_default_column_width_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) }, Op::Communicate(1),
        Op::CompleteAnimations,
    ]
}
#[test]
fn default_column_width_fixed() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, default_column_width_fixed_ops());
    assert_golden!(layout.snapshot(), "default_column_width_fixed");
}
#[test]
fn different_default_column_width() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, different_default_column_width_ops());
    assert_golden!(layout.snapshot(), "different_default_column_width");
}
#[test]
fn default_column_width_fixed_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, default_column_width_fixed_ops());
    assert_golden_rtl!(layout, "default_column_width_fixed");
}
#[test]
fn different_default_column_width_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, different_default_column_width_ops());
    assert_golden_rtl!(layout, "different_default_column_width");
}
