//! Golden tests for 080_column_resize
//!
//! AUTO-GENERATED by `cargo xtask sync-golden`
use super::*;
fn column_resize_1_ops() -> Vec<Op> {
    vec![
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)), Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}
fn column_resize_2_ops() -> Vec<Op> {
    vec![
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)), Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}
#[test]
fn column_resize_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, column_resize_1_ops());
    assert_golden!(layout.snapshot(), "column_resize_1");
}
#[test]
fn column_resize_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, column_resize_2_ops());
    assert_golden!(layout.snapshot(), "column_resize_2");
}
#[test]
fn column_resize_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, column_resize_1_ops());
    assert_golden_rtl!(layout, "column_resize_1");
}
#[test]
fn column_resize_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, column_resize_2_ops());
    assert_golden_rtl!(layout, "column_resize_2");
}
