//! Golden tests for 130_column_move
//!
//! AUTO-GENERATED by `cargo xtask sync-golden`
use super::*;
fn move_column_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft, Op::MoveColumnRight, Op::Communicate(1), Op::Communicate(2),
        Op::Communicate(3), Op::CompleteAnimations,
    ]
}
#[test]
fn move_column() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, move_column_ops());
    assert_golden!(layout.snapshot(), "move_column");
}
#[test]
fn move_column_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, move_column_ops());
    assert_golden_rtl!(layout, "move_column");
}
