// Golden tests for 250_gaps_struts
//
// AUTO-GENERATED by `cargo xtask sync-golden`

use super::*;

// ============================================================================
// Test Operations (extracted from snapshot tests)
// ============================================================================

fn very_large_gaps_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params: TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::AddWindow { params: TestWindowParams::new(2) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::Communicate(1),
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn very_large_struts_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params: TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(50.0)),
        Op::Communicate(1),
        Op::CompleteAnimations,
    ]
}

fn zero_gaps_explicit_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params: TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::AddWindow { params: TestWindowParams::new(2) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::AddWindow { params: TestWindowParams::new(3) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)),
        Op::Communicate(1),
        Op::Communicate(2),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

// ============================================================================
// LTR Tests
// ============================================================================

#[test]
fn very_large_gaps() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, very_large_gaps_ops());
    assert_golden!(layout.snapshot(), "very_large_gaps");
}

#[test]
fn very_large_struts() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, very_large_struts_ops());
    assert_golden!(layout.snapshot(), "very_large_struts");
}

#[test]
fn zero_gaps_explicit() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, zero_gaps_explicit_ops());
    assert_golden!(layout.snapshot(), "zero_gaps_explicit");
}

// ============================================================================
// RTL Tests
// ============================================================================

#[test]
fn very_large_gaps_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, very_large_gaps_ops());
    assert_golden_rtl!(layout, "very_large_gaps");
}

#[test]
fn very_large_struts_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, very_large_struts_ops());
    assert_golden_rtl!(layout, "very_large_struts");
}

#[test]
fn zero_gaps_explicit_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, zero_gaps_explicit_ops());
    assert_golden_rtl!(layout, "zero_gaps_explicit");
}

