//! Golden tests for 330_anim_column_movement
//!
//! AUTO-GENERATED by `cargo xtask sync-golden`
use super::*;
fn anim_move_column_left_1_ops() -> Vec<Op> {
    vec![Op::MoveColumnLeft]
}
fn anim_move_column_left_2_ops() -> Vec<Op> {
    vec![Op::MoveColumnLeft]
}
fn anim_move_column_left_3_ops() -> Vec<Op> {
    vec![]
}
fn anim_move_column_right_1_ops() -> Vec<Op> {
    vec![Op::MoveColumnRight]
}
fn anim_move_column_right_2_ops() -> Vec<Op> {
    vec![Op::MoveColumnRight]
}
fn anim_move_column_right_3_ops() -> Vec<Op> {
    vec![]
}
fn anim_move_column_right_4_ops() -> Vec<Op> {
    vec![]
}
fn anim_move_column_to_first_1_ops() -> Vec<Op> {
    vec![Op::MoveColumnToFirst]
}
fn anim_move_column_to_first_2_ops() -> Vec<Op> {
    vec![]
}
fn anim_move_column_to_last_1_ops() -> Vec<Op> {
    vec![Op::MoveColumnToLast]
}
fn anim_move_column_to_last_2_ops() -> Vec<Op> {
    vec![]
}
#[test]
fn anim_move_column_left_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, anim_move_column_left_1_ops());
    assert_golden!(layout.snapshot(), "anim_move_column_left_1");
}
#[test]
fn anim_move_column_left_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, anim_move_column_left_2_ops());
    assert_golden!(layout.snapshot(), "anim_move_column_left_2");
}
#[test]
fn anim_move_column_left_3() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, anim_move_column_left_3_ops());
    assert_golden!(layout.snapshot(), "anim_move_column_left_3");
}
#[test]
fn anim_move_column_right_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, anim_move_column_right_1_ops());
    assert_golden!(layout.snapshot(), "anim_move_column_right_1");
}
#[test]
fn anim_move_column_right_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, anim_move_column_right_2_ops());
    assert_golden!(layout.snapshot(), "anim_move_column_right_2");
}
#[test]
fn anim_move_column_right_3() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, anim_move_column_right_3_ops());
    assert_golden!(layout.snapshot(), "anim_move_column_right_3");
}
#[test]
fn anim_move_column_right_4() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, anim_move_column_right_4_ops());
    assert_golden!(layout.snapshot(), "anim_move_column_right_4");
}
#[test]
fn anim_move_column_to_first_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, anim_move_column_to_first_1_ops());
    assert_golden!(layout.snapshot(), "anim_move_column_to_first_1");
}
#[test]
fn anim_move_column_to_first_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, anim_move_column_to_first_2_ops());
    assert_golden!(layout.snapshot(), "anim_move_column_to_first_2");
}
#[test]
fn anim_move_column_to_last_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, anim_move_column_to_last_1_ops());
    assert_golden!(layout.snapshot(), "anim_move_column_to_last_1");
}
#[test]
fn anim_move_column_to_last_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, anim_move_column_to_last_2_ops());
    assert_golden!(layout.snapshot(), "anim_move_column_to_last_2");
}
#[test]
fn anim_move_column_left_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, anim_move_column_left_1_ops());
    assert_golden_rtl!(layout, "anim_move_column_left_1");
}
#[test]
fn anim_move_column_left_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, anim_move_column_left_2_ops());
    assert_golden_rtl!(layout, "anim_move_column_left_2");
}
#[test]
fn anim_move_column_left_3_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, anim_move_column_left_3_ops());
    assert_golden_rtl!(layout, "anim_move_column_left_3");
}
#[test]
fn anim_move_column_right_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, anim_move_column_right_1_ops());
    assert_golden_rtl!(layout, "anim_move_column_right_1");
}
#[test]
fn anim_move_column_right_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, anim_move_column_right_2_ops());
    assert_golden_rtl!(layout, "anim_move_column_right_2");
}
#[test]
fn anim_move_column_right_3_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, anim_move_column_right_3_ops());
    assert_golden_rtl!(layout, "anim_move_column_right_3");
}
#[test]
fn anim_move_column_right_4_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, anim_move_column_right_4_ops());
    assert_golden_rtl!(layout, "anim_move_column_right_4");
}
#[test]
fn anim_move_column_to_first_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, anim_move_column_to_first_1_ops());
    assert_golden_rtl!(layout, "anim_move_column_to_first_1");
}
#[test]
fn anim_move_column_to_first_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, anim_move_column_to_first_2_ops());
    assert_golden_rtl!(layout, "anim_move_column_to_first_2");
}
#[test]
fn anim_move_column_to_last_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, anim_move_column_to_last_1_ops());
    assert_golden_rtl!(layout, "anim_move_column_to_last_1");
}
#[test]
fn anim_move_column_to_last_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, anim_move_column_to_last_2_ops());
    assert_golden_rtl!(layout, "anim_move_column_to_last_2");
}
