//! Golden tests for 320_config_variants
//!
//! AUTO-GENERATED by `cargo xtask sync-golden`
use super::*;
fn empty_workspace_above_first_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(50.0)), Op::AddWindow { params :
        TestWindowParams::new(2) }, Op::SetColumnWidth(SizeChange::SetProportion(50.0)),
        Op::Communicate(1), Op::Communicate(2), Op::CompleteAnimations,
    ]
}
fn gaps_struts_and_centering_combined_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)), Op::AddWindow {
        params : TestWindowParams::new(2) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)), Op::AddWindow {
        params : TestWindowParams::new(3) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)), Op::AddWindow {
        params : TestWindowParams::new(4) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)), Op::Communicate(1),
        Op::Communicate(2), Op::Communicate(3), Op::Communicate(4),
        Op::CompleteAnimations,
    ]
}
fn preset_width_switch_rightmost_column_1_ops() -> Vec<Op> {
    vec![Op::SwitchPresetColumnWidth, Op::Communicate(3),]
}
fn preset_width_switch_rightmost_column_2_ops() -> Vec<Op> {
    vec![Op::SwitchPresetColumnWidth, Op::Communicate(3),]
}
fn preset_width_switch_rightmost_column_3_ops() -> Vec<Op> {
    vec![Op::SwitchPresetColumnWidth, Op::Communicate(3),]
}
fn preset_width_switch_rightmost_column_4_ops() -> Vec<Op> {
    vec![Op::SwitchPresetColumnWidth, Op::Communicate(3),]
}
fn preset_widths_with_gaps_1_ops() -> Vec<Op> {
    vec![Op::SwitchPresetColumnWidth, Op::Communicate(2), Op::CompleteAnimations,]
}
fn preset_widths_with_gaps_2_ops() -> Vec<Op> {
    vec![Op::SwitchPresetColumnWidth, Op::Communicate(2), Op::CompleteAnimations,]
}
fn preset_widths_with_gaps_3_ops() -> Vec<Op> {
    vec![Op::SwitchPresetColumnWidth, Op::Communicate(2), Op::CompleteAnimations,]
}
#[test]
fn empty_workspace_above_first() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, empty_workspace_above_first_ops());
    assert_golden!(layout.snapshot(), "empty_workspace_above_first");
}
#[test]
fn gaps_struts_and_centering_combined() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, gaps_struts_and_centering_combined_ops());
    assert_golden!(layout.snapshot(), "gaps_struts_and_centering_combined");
}
#[test]
fn preset_width_switch_rightmost_column_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_width_switch_rightmost_column_1_ops());
    assert_golden!(layout.snapshot(), "preset_width_switch_rightmost_column_1");
}
#[test]
fn preset_width_switch_rightmost_column_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_width_switch_rightmost_column_2_ops());
    assert_golden!(layout.snapshot(), "preset_width_switch_rightmost_column_2");
}
#[test]
fn preset_width_switch_rightmost_column_3() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_width_switch_rightmost_column_3_ops());
    assert_golden!(layout.snapshot(), "preset_width_switch_rightmost_column_3");
}
#[test]
fn preset_width_switch_rightmost_column_4() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_width_switch_rightmost_column_4_ops());
    assert_golden!(layout.snapshot(), "preset_width_switch_rightmost_column_4");
}
#[test]
fn preset_widths_with_gaps_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_widths_with_gaps_1_ops());
    assert_golden!(layout.snapshot(), "preset_widths_with_gaps_1");
}
#[test]
fn preset_widths_with_gaps_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_widths_with_gaps_2_ops());
    assert_golden!(layout.snapshot(), "preset_widths_with_gaps_2");
}
#[test]
fn preset_widths_with_gaps_3() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, preset_widths_with_gaps_3_ops());
    assert_golden!(layout.snapshot(), "preset_widths_with_gaps_3");
}
#[test]
fn empty_workspace_above_first_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, empty_workspace_above_first_ops());
    assert_golden_rtl!(layout, "empty_workspace_above_first");
}
#[test]
fn gaps_struts_and_centering_combined_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, gaps_struts_and_centering_combined_ops());
    assert_golden_rtl!(layout, "gaps_struts_and_centering_combined");
}
#[test]
fn preset_width_switch_rightmost_column_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_width_switch_rightmost_column_1_ops());
    assert_golden_rtl!(layout, "preset_width_switch_rightmost_column_1");
}
#[test]
fn preset_width_switch_rightmost_column_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_width_switch_rightmost_column_2_ops());
    assert_golden_rtl!(layout, "preset_width_switch_rightmost_column_2");
}
#[test]
fn preset_width_switch_rightmost_column_3_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_width_switch_rightmost_column_3_ops());
    assert_golden_rtl!(layout, "preset_width_switch_rightmost_column_3");
}
#[test]
fn preset_width_switch_rightmost_column_4_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_width_switch_rightmost_column_4_ops());
    assert_golden_rtl!(layout, "preset_width_switch_rightmost_column_4");
}
#[test]
fn preset_widths_with_gaps_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_widths_with_gaps_1_ops());
    assert_golden_rtl!(layout, "preset_widths_with_gaps_1");
}
#[test]
fn preset_widths_with_gaps_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_widths_with_gaps_2_ops());
    assert_golden_rtl!(layout, "preset_widths_with_gaps_2");
}
#[test]
fn preset_widths_with_gaps_3_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, preset_widths_with_gaps_3_ops());
    assert_golden_rtl!(layout, "preset_widths_with_gaps_3");
}
