// Golden tests for 290_resize_during_ops
//
// AUTO-GENERATED by `cargo xtask sync-golden`

use super::*;

// ============================================================================
// Test Operations (extracted from snapshot tests)
// ============================================================================

fn close_column_while_moving_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::FocusColumnLeft,
        Op::MoveColumnRight,
        Op::CloseWindow(2),
        Op::Communicate(1),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn close_column_while_resizing_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::SetColumnWidth(SizeChange::SetProportion(50.0)),
        Op::CloseWindow(2),
        Op::Communicate(1),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

// ============================================================================
// LTR Tests
// ============================================================================

#[test]
fn close_column_while_moving() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, close_column_while_moving_ops());
    assert_golden!(layout.snapshot(), "close_column_while_moving");
}

#[test]
fn close_column_while_resizing() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, close_column_while_resizing_ops());
    assert_golden!(layout.snapshot(), "close_column_while_resizing");
}

// ============================================================================
// RTL Tests
// ============================================================================

#[test]
fn close_column_while_moving_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, close_column_while_moving_ops());
    assert_golden_rtl!(layout, "close_column_while_moving");
}

#[test]
fn close_column_while_resizing_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, close_column_while_resizing_ops());
    assert_golden_rtl!(layout, "close_column_while_resizing");
}

