//! Golden tests for 030_column_positions
//!
//! AUTO-GENERATED by `cargo xtask sync-golden`
use super::*;
fn column_x_positions_mixed_widths_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetFixed(200)), Op::AddWindow { params :
        TestWindowParams::new(2) }, Op::SetColumnWidth(SizeChange::SetProportion(50.0)),
        Op::AddWindow { params : TestWindowParams::new(3) },
        Op::SetColumnWidth(SizeChange::SetFixed(300)), Op::Communicate(1),
        Op::Communicate(2), Op::Communicate(3), Op::CompleteAnimations,
    ]
}
fn column_x_positions_three_columns_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)), Op::AddWindow {
        params : TestWindowParams::new(2) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)), Op::AddWindow {
        params : TestWindowParams::new(3) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)), Op::Communicate(1),
        Op::Communicate(2), Op::Communicate(3), Op::CompleteAnimations,
    ]
}
fn column_x_positions_two_columns_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)), Op::AddWindow {
        params : TestWindowParams::new(2) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)), Op::Communicate(1),
        Op::Communicate(2), Op::CompleteAnimations,
    ]
}
fn mixed_column_widths_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetFixed(200)), Op::AddWindow { params :
        TestWindowParams::new(2) }, Op::SetColumnWidth(SizeChange::SetProportion(50.0)),
        Op::AddWindow { params : TestWindowParams::new(3) },
        Op::SetColumnWidth(SizeChange::SetFixed(300)), Op::Communicate(1),
        Op::Communicate(2), Op::Communicate(3), Op::CompleteAnimations,
    ]
}
#[test]
fn column_x_positions_mixed_widths() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, column_x_positions_mixed_widths_ops());
    assert_golden!(layout.snapshot(), "column_x_positions_mixed_widths");
}
#[test]
fn column_x_positions_three_columns() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, column_x_positions_three_columns_ops());
    assert_golden!(layout.snapshot(), "column_x_positions_three_columns");
}
#[test]
fn column_x_positions_two_columns() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, column_x_positions_two_columns_ops());
    assert_golden!(layout.snapshot(), "column_x_positions_two_columns");
}
#[test]
fn mixed_column_widths() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, mixed_column_widths_ops());
    assert_golden!(layout.snapshot(), "mixed_column_widths");
}
#[test]
fn column_x_positions_mixed_widths_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, column_x_positions_mixed_widths_ops());
    assert_golden_rtl!(layout, "column_x_positions_mixed_widths");
}
#[test]
fn column_x_positions_three_columns_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, column_x_positions_three_columns_ops());
    assert_golden_rtl!(layout, "column_x_positions_three_columns");
}
#[test]
fn column_x_positions_two_columns_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, column_x_positions_two_columns_ops());
    assert_golden_rtl!(layout, "column_x_positions_two_columns");
}
#[test]
fn mixed_column_widths_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, mixed_column_widths_ops());
    assert_golden_rtl!(layout, "mixed_column_widths");
}
