//! Golden tests for 240_scale_factors
//!
//! AUTO-GENERATED by `cargo xtask sync-golden`
use super::*;
fn scale_factor_1_5_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)), Op::AddWindow {
        params : TestWindowParams::new(2) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)), Op::Communicate(1),
        Op::Communicate(2), Op::CompleteAnimations,
    ]
}
fn scale_factor_2_0_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(50.0)), Op::AddWindow { params :
        TestWindowParams::new(2) }, Op::SetColumnWidth(SizeChange::SetProportion(50.0)),
        Op::Communicate(1), Op::Communicate(2), Op::CompleteAnimations,
    ]
}
fn scale_factor_with_gaps_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)), Op::AddWindow {
        params : TestWindowParams::new(2) },
        Op::SetColumnWidth(SizeChange::SetProportion(100.0 / 3.0)), Op::Communicate(1),
        Op::Communicate(2), Op::CompleteAnimations,
    ]
}
#[test]
fn scale_factor_1_5() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, scale_factor_1_5_ops());
    assert_golden!(layout.snapshot(), "scale_factor_1_5");
}
#[test]
fn scale_factor_2_0() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, scale_factor_2_0_ops());
    assert_golden!(layout.snapshot(), "scale_factor_2_0");
}
#[test]
fn scale_factor_with_gaps() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, scale_factor_with_gaps_ops());
    assert_golden!(layout.snapshot(), "scale_factor_with_gaps");
}
#[test]
fn scale_factor_1_5_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, scale_factor_1_5_ops());
    assert_golden_rtl!(layout, "scale_factor_1_5");
}
#[test]
fn scale_factor_2_0_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, scale_factor_2_0_ops());
    assert_golden_rtl!(layout, "scale_factor_2_0");
}
#[test]
fn scale_factor_with_gaps_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, scale_factor_with_gaps_ops());
    assert_golden_rtl!(layout, "scale_factor_with_gaps");
}
