// Golden tests for 110_resize_advanced
//
// AUTO-GENERATED by `cargo xtask sync-golden`

use super::*;

// ============================================================================
// Test Operations (extracted from snapshot tests)
// ============================================================================

fn resize_while_scrolled_overflow_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::FocusColumnLeft,
        Op::SetColumnWidth(SizeChange::SetProportion(50.0)),
        Op::Communicate(1),
        Op::Communicate(2),
        Op::Communicate(3),
        Op::Communicate(4),
        Op::CompleteAnimations,
    ]
}

fn resize_with_multiple_tiles_open_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::SetColumnWidth(SizeChange::SetProportion(50.0)),
        Op::Communicate(1),
        Op::Communicate(2),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

// ============================================================================
// LTR Tests
// ============================================================================

#[test]
fn resize_while_scrolled_overflow() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, resize_while_scrolled_overflow_ops());
    assert_golden!(layout.snapshot(), "resize_while_scrolled_overflow");
}

#[test]
fn resize_with_multiple_tiles_open() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, resize_with_multiple_tiles_open_ops());
    assert_golden!(layout.snapshot(), "resize_with_multiple_tiles_open");
}

// ============================================================================
// RTL Tests
// ============================================================================

#[test]
fn resize_while_scrolled_overflow_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, resize_while_scrolled_overflow_ops());
    assert_golden_rtl!(layout, "resize_while_scrolled_overflow");
}

#[test]
fn resize_with_multiple_tiles_open_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, resize_with_multiple_tiles_open_ops());
    assert_golden_rtl!(layout, "resize_with_multiple_tiles_open");
}

