//! Golden tests for 370_active_tile_visibility
//!
//! AUTO-GENERATED by `cargo xtask sync-golden`
use super::*;
fn active_tile_viewport_y_position_ops() -> Vec<Op> {
    vec![Op::FocusWindowDown]
}
fn active_tile_visibility_with_large_columns_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) }, Op::AddWindow { params :
        TestWindowParams::new(2) }, Op::AddWindow { params : TestWindowParams::new(3) },
        Op::Communicate(1), Op::Communicate(2), Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}
fn active_tile_visible_after_scroll_ops() -> Vec<Op> {
    vec![
        Op::AddWindow { params : TestWindowParams::new(1) }, Op::AddWindow { params :
        TestWindowParams::new(2) }, Op::AddWindow { params : TestWindowParams::new(3) },
        Op::Communicate(1), Op::Communicate(2), Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}
#[test]
fn active_tile_viewport_y_position() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, active_tile_viewport_y_position_ops());
    assert_golden!(layout.snapshot(), "active_tile_viewport_y_position");
}
#[test]
fn active_tile_visibility_with_large_columns() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, active_tile_visibility_with_large_columns_ops());
    assert_golden!(layout.snapshot(), "active_tile_visibility_with_large_columns");
}
#[test]
fn active_tile_visible_after_scroll() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, active_tile_visible_after_scroll_ops());
    assert_golden!(layout.snapshot(), "active_tile_visible_after_scroll");
}
#[test]
fn active_tile_viewport_y_position_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, active_tile_viewport_y_position_ops());
    assert_golden_rtl!(layout, "active_tile_viewport_y_position");
}
#[test]
fn active_tile_visibility_with_large_columns_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, active_tile_visibility_with_large_columns_ops());
    assert_golden_rtl!(layout, "active_tile_visibility_with_large_columns");
}
#[test]
fn active_tile_visible_after_scroll_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, active_tile_visible_after_scroll_ops());
    assert_golden_rtl!(layout, "active_tile_visible_after_scroll");
}
