// Golden tests for 070_window_closing
//
// AUTO-GENERATED by `cargo xtask sync-golden`

use super::*;

// ============================================================================
// Test Operations (extracted from snapshot tests)
// ============================================================================

fn closing_first_of_three_fifths_preset_1_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::FocusColumnLeft,
        Op::CloseWindow(1),
        Op::Communicate(2),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn closing_first_of_three_fifths_preset_2_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::FocusColumnLeft,
        Op::CloseWindow(1),
        Op::Communicate(2),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn closing_first_of_three_thirds_preset_1_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::FocusColumnLeft,
        Op::CloseWindow(1),
        Op::Communicate(2),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn closing_first_of_three_thirds_preset_2_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::FocusColumnLeft,
        Op::CloseWindow(1),
        Op::Communicate(2),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn closing_last_of_three_fifths_preset_ops() -> Vec<Op> {
    vec![
        Op::CloseWindow(3),
        Op::Communicate(1),
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn closing_last_of_three_thirds_preset_ops() -> Vec<Op> {
    vec![
        Op::CloseWindow(3),
        Op::Communicate(1),
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn closing_leftmost_column_with_overflow_1_ops() -> Vec<Op> {
    vec![
        Op::CloseWindow(1),
        Op::Communicate(2),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn closing_leftmost_column_with_overflow_2_ops() -> Vec<Op> {
    vec![
        Op::CloseWindow(1),
        Op::Communicate(2),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn closing_middle_column_with_overflow_1_ops() -> Vec<Op> {
    vec![
        Op::CloseWindow(2),
        Op::Communicate(1),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn closing_middle_column_with_overflow_2_ops() -> Vec<Op> {
    vec![
        Op::CloseWindow(2),
        Op::Communicate(1),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn closing_middle_of_three_fifths_preset_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::CloseWindow(2),
        Op::Communicate(1),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn closing_middle_of_three_thirds_preset_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::CloseWindow(2),
        Op::Communicate(1),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn closing_mixed_preset_sizes_1_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::CloseWindow(2),
        Op::Communicate(1),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn closing_mixed_preset_sizes_2_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::CloseWindow(2),
        Op::Communicate(1),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn closing_rightmost_column_with_overflow_1_ops() -> Vec<Op> {
    vec![
        Op::CloseWindow(3),
        Op::Communicate(1),
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn closing_rightmost_column_with_overflow_2_ops() -> Vec<Op> {
    vec![
        Op::CloseWindow(3),
        Op::Communicate(1),
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn closing_with_gaps_1_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::CloseWindow(2),
        Op::Communicate(1),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn closing_with_gaps_2_ops() -> Vec<Op> {
    vec![
        Op::FocusColumnLeft,
        Op::CloseWindow(2),
        Op::Communicate(1),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn closing_with_gaps_and_struts_1_ops() -> Vec<Op> {
    vec![
        Op::CloseWindow(3),
        Op::Communicate(1),
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn closing_with_gaps_and_struts_2_ops() -> Vec<Op> {
    vec![
        Op::CloseWindow(3),
        Op::Communicate(1),
        Op::Communicate(2),
        Op::CompleteAnimations,
    ]
}

fn window_closing_1_ops() -> Vec<Op> {
    vec![
        Op::CloseWindow(2),
        Op::Communicate(1),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

fn window_closing_2_ops() -> Vec<Op> {
    vec![
        Op::CloseWindow(2),
        Op::Communicate(1),
        Op::Communicate(3),
        Op::CompleteAnimations,
    ]
}

// ============================================================================
// LTR Tests
// ============================================================================

#[test]
fn closing_first_of_three_fifths_preset_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_first_of_three_fifths_preset_1_ops());
    assert_golden!(layout.snapshot(), "closing_first_of_three_fifths_preset_1");
}

#[test]
fn closing_first_of_three_fifths_preset_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_first_of_three_fifths_preset_2_ops());
    assert_golden!(layout.snapshot(), "closing_first_of_three_fifths_preset_2");
}

#[test]
fn closing_first_of_three_thirds_preset_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_first_of_three_thirds_preset_1_ops());
    assert_golden!(layout.snapshot(), "closing_first_of_three_thirds_preset_1");
}

#[test]
fn closing_first_of_three_thirds_preset_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_first_of_three_thirds_preset_2_ops());
    assert_golden!(layout.snapshot(), "closing_first_of_three_thirds_preset_2");
}

#[test]
fn closing_last_of_three_fifths_preset() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_last_of_three_fifths_preset_ops());
    assert_golden!(layout.snapshot(), "closing_last_of_three_fifths_preset");
}

#[test]
fn closing_last_of_three_thirds_preset() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_last_of_three_thirds_preset_ops());
    assert_golden!(layout.snapshot(), "closing_last_of_three_thirds_preset");
}

#[test]
fn closing_leftmost_column_with_overflow_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_leftmost_column_with_overflow_1_ops());
    assert_golden!(layout.snapshot(), "closing_leftmost_column_with_overflow_1");
}

#[test]
fn closing_leftmost_column_with_overflow_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_leftmost_column_with_overflow_2_ops());
    assert_golden!(layout.snapshot(), "closing_leftmost_column_with_overflow_2");
}

#[test]
fn closing_middle_column_with_overflow_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_middle_column_with_overflow_1_ops());
    assert_golden!(layout.snapshot(), "closing_middle_column_with_overflow_1");
}

#[test]
fn closing_middle_column_with_overflow_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_middle_column_with_overflow_2_ops());
    assert_golden!(layout.snapshot(), "closing_middle_column_with_overflow_2");
}

#[test]
fn closing_middle_of_three_fifths_preset() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_middle_of_three_fifths_preset_ops());
    assert_golden!(layout.snapshot(), "closing_middle_of_three_fifths_preset");
}

#[test]
fn closing_middle_of_three_thirds_preset() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_middle_of_three_thirds_preset_ops());
    assert_golden!(layout.snapshot(), "closing_middle_of_three_thirds_preset");
}

#[test]
fn closing_mixed_preset_sizes_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_mixed_preset_sizes_1_ops());
    assert_golden!(layout.snapshot(), "closing_mixed_preset_sizes_1");
}

#[test]
fn closing_mixed_preset_sizes_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_mixed_preset_sizes_2_ops());
    assert_golden!(layout.snapshot(), "closing_mixed_preset_sizes_2");
}

#[test]
fn closing_rightmost_column_with_overflow_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_rightmost_column_with_overflow_1_ops());
    assert_golden!(layout.snapshot(), "closing_rightmost_column_with_overflow_1");
}

#[test]
fn closing_rightmost_column_with_overflow_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_rightmost_column_with_overflow_2_ops());
    assert_golden!(layout.snapshot(), "closing_rightmost_column_with_overflow_2");
}

#[test]
fn closing_with_gaps_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_with_gaps_1_ops());
    assert_golden!(layout.snapshot(), "closing_with_gaps_1");
}

#[test]
fn closing_with_gaps_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_with_gaps_2_ops());
    assert_golden!(layout.snapshot(), "closing_with_gaps_2");
}

#[test]
fn closing_with_gaps_and_struts_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_with_gaps_and_struts_1_ops());
    assert_golden!(layout.snapshot(), "closing_with_gaps_and_struts_1");
}

#[test]
fn closing_with_gaps_and_struts_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, closing_with_gaps_and_struts_2_ops());
    assert_golden!(layout.snapshot(), "closing_with_gaps_and_struts_2");
}

#[test]
fn window_closing_1() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, window_closing_1_ops());
    assert_golden!(layout.snapshot(), "window_closing_1");
}

#[test]
fn window_closing_2() {
    let mut layout = set_up_empty();
    check_ops_on_layout(&mut layout, window_closing_2_ops());
    assert_golden!(layout.snapshot(), "window_closing_2");
}

// ============================================================================
// RTL Tests
// ============================================================================

#[test]
fn closing_first_of_three_fifths_preset_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_first_of_three_fifths_preset_1_ops());
    assert_golden_rtl!(layout, "closing_first_of_three_fifths_preset_1");
}

#[test]
fn closing_first_of_three_fifths_preset_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_first_of_three_fifths_preset_2_ops());
    assert_golden_rtl!(layout, "closing_first_of_three_fifths_preset_2");
}

#[test]
fn closing_first_of_three_thirds_preset_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_first_of_three_thirds_preset_1_ops());
    assert_golden_rtl!(layout, "closing_first_of_three_thirds_preset_1");
}

#[test]
fn closing_first_of_three_thirds_preset_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_first_of_three_thirds_preset_2_ops());
    assert_golden_rtl!(layout, "closing_first_of_three_thirds_preset_2");
}

#[test]
fn closing_last_of_three_fifths_preset_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_last_of_three_fifths_preset_ops());
    assert_golden_rtl!(layout, "closing_last_of_three_fifths_preset");
}

#[test]
fn closing_last_of_three_thirds_preset_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_last_of_three_thirds_preset_ops());
    assert_golden_rtl!(layout, "closing_last_of_three_thirds_preset");
}

#[test]
fn closing_leftmost_column_with_overflow_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_leftmost_column_with_overflow_1_ops());
    assert_golden_rtl!(layout, "closing_leftmost_column_with_overflow_1");
}

#[test]
fn closing_leftmost_column_with_overflow_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_leftmost_column_with_overflow_2_ops());
    assert_golden_rtl!(layout, "closing_leftmost_column_with_overflow_2");
}

#[test]
fn closing_middle_column_with_overflow_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_middle_column_with_overflow_1_ops());
    assert_golden_rtl!(layout, "closing_middle_column_with_overflow_1");
}

#[test]
fn closing_middle_column_with_overflow_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_middle_column_with_overflow_2_ops());
    assert_golden_rtl!(layout, "closing_middle_column_with_overflow_2");
}

#[test]
fn closing_middle_of_three_fifths_preset_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_middle_of_three_fifths_preset_ops());
    assert_golden_rtl!(layout, "closing_middle_of_three_fifths_preset");
}

#[test]
fn closing_middle_of_three_thirds_preset_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_middle_of_three_thirds_preset_ops());
    assert_golden_rtl!(layout, "closing_middle_of_three_thirds_preset");
}

#[test]
fn closing_mixed_preset_sizes_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_mixed_preset_sizes_1_ops());
    assert_golden_rtl!(layout, "closing_mixed_preset_sizes_1");
}

#[test]
fn closing_mixed_preset_sizes_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_mixed_preset_sizes_2_ops());
    assert_golden_rtl!(layout, "closing_mixed_preset_sizes_2");
}

#[test]
fn closing_rightmost_column_with_overflow_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_rightmost_column_with_overflow_1_ops());
    assert_golden_rtl!(layout, "closing_rightmost_column_with_overflow_1");
}

#[test]
fn closing_rightmost_column_with_overflow_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_rightmost_column_with_overflow_2_ops());
    assert_golden_rtl!(layout, "closing_rightmost_column_with_overflow_2");
}

#[test]
fn closing_with_gaps_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_with_gaps_1_ops());
    assert_golden_rtl!(layout, "closing_with_gaps_1");
}

#[test]
fn closing_with_gaps_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_with_gaps_2_ops());
    assert_golden_rtl!(layout, "closing_with_gaps_2");
}

#[test]
fn closing_with_gaps_and_struts_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_with_gaps_and_struts_1_ops());
    assert_golden_rtl!(layout, "closing_with_gaps_and_struts_1");
}

#[test]
fn closing_with_gaps_and_struts_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, closing_with_gaps_and_struts_2_ops());
    assert_golden_rtl!(layout, "closing_with_gaps_and_struts_2");
}

#[test]
fn window_closing_1_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, window_closing_1_ops());
    assert_golden_rtl!(layout, "window_closing_1");
}

#[test]
fn window_closing_2_rtl() {
    let mut layout = set_up_empty_rtl();
    check_ops_on_layout(&mut layout, window_closing_2_ops());
    assert_golden_rtl!(layout, "window_closing_2");
}

